export const DI_TOKENS = {
  GameApplication: Symbol.for('GameApplication'),
  SceneRoot: Symbol.for('SceneRoot'),
  GameLoop: Symbol.for('GameLoop'),
  AssetService: Symbol.for('AssetService'),
  GameWorld: Symbol.for('GameWorld'),
  SpriteStore: Symbol.for('SpriteStore'),
  SpineStore: Symbol.for('SpineStore'),
  GameCommands: Symbol.for('GameCommands'),
  BunnySpawnerService: Symbol.for('BunnySpawnerService'),
  SpineSpawnerService: Symbol.for('SpineSpawnerService'),
  SpineService: Symbol.for('SpineService'),
  CameraBootstrapService: Symbol.for('CameraBootstrapService'),
  CameraCommandService: Symbol.for('CameraCommandService'),
  MovementSystem: Symbol.for('MovementSystem'),
  BounceSystem: Symbol.for('BounceSystem'),
  CameraSystem: Symbol.for('CameraSystem'),
  TweenRuntimeStore: Symbol.for('TweenRuntimeStore'),
  TweenSystem: Symbol.for('TweenSystem'),
  TweenService: Symbol.for('TweenService'),
  SpineSystem: Symbol.for('SpineSystem'),
  RenderSystem: Symbol.for('RenderSystem'),
  SlotService: Symbol.for('SlotService'),
  SlotSystem: Symbol.for('SlotSystem'),
  Systems: Symbol.for('Systems'),
} as const
