import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { packAsync } from 'free-tex-packer-core'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const rawRoot = path.join(root, 'raw_assets')
const outRoot = path.join(root, 'public', 'assets')
const generatedRoot = path.join(root, 'src', 'assets', 'generated')

const IMAGE_EXT = new Set(['.png', '.jpg', '.jpeg', '.webp'])

function toFrameKey(relativePath: string): string {
  const withoutExt = relativePath.replace(/\.[^.]+$/, '')
  return withoutExt.split(/[\\/]/).join('_')
}

function toPropName(frameKey: string): string {
  const parts = frameKey.split('_')
  return parts
    .map((part, index) => {
      const cleaned = part.replace(/[^a-zA-Z0-9]/g, '')
      if (!cleaned) return 'frame'
      if (index === 0) {
        return /^[0-9]/.test(cleaned) ? `f${cleaned}` : cleaned
      }
      return cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
    })
    .join('')
}

function collectImages(dir: string, base = ''): Array<{ path: string; contents: Buffer; frameKey: string }> {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const images: Array<{ path: string; contents: Buffer; frameKey: string }> = []

  for (const entry of entries) {
    const rel = base ? `${base}/${entry.name}` : entry.name
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      images.push(...collectImages(full, rel))
      continue
    }
    if (!IMAGE_EXT.has(path.extname(entry.name).toLowerCase())) continue
    const frameKey = toFrameKey(rel)
    images.push({
      path: `${frameKey}${path.extname(entry.name)}`,
      contents: fs.readFileSync(full),
      frameKey,
    })
  }

  return images
}

function toDataUrl(buffer: Buffer, mime: string): string {
  return `data:${mime};base64,${buffer.toString('base64')}`
}

function mimeForExt(ext: string): string {
  switch (ext.toLowerCase()) {
    case '.jpg':
    case '.jpeg':
      return 'image/jpeg'
    case '.webp':
      return 'image/webp'
    default:
      return 'image/png'
  }
}

function writeEmbeddedAssets(atlasNames: string[]) {
  const spritesheetBlocks = atlasNames
    .sort()
    .map((name) => {
      const jsonPath = path.join(outRoot, `${name}.json`)
      const imagePath = path.join(outRoot, `${name}.png`)
      const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'))
      const image = toDataUrl(fs.readFileSync(imagePath), 'image/png')
      return `  ${name}: {\n    data: ${JSON.stringify(data)} as SpritesheetData,\n    image: ${JSON.stringify(image)},\n  },`
    })
    .join('\n')

  const publicDir = path.join(root, 'public')
  const imageEntries: string[] = []

  if (fs.existsSync(publicDir)) {
    for (const file of fs.readdirSync(publicDir)) {
      const ext = path.extname(file).toLowerCase()
      if (!IMAGE_EXT.has(ext)) continue
      const key = toPropName(file.replace(/\.[^.]+$/, ''))
      const full = path.join(publicDir, file)
      imageEntries.push(`  ${key}: ${JSON.stringify(toDataUrl(fs.readFileSync(full), mimeForExt(ext)))},`)
    }
  }

  imageEntries.sort()

  fs.writeFileSync(
    path.join(generatedRoot, 'embeddedAssets.ts'),
    `// Auto-generated by scripts/pack-assets.ts — do not edit.\nimport type { SpritesheetData } from 'pixi.js'\n\nexport type EmbeddedSpritesheet = {\n  data: SpritesheetData\n  image: string\n}\n\nexport const EmbeddedSpritesheets = {\n${spritesheetBlocks}\n} as const\n\nexport type EmbeddedAtlasName = keyof typeof EmbeddedSpritesheets\n\nexport const EmbeddedImages = {\n${imageEntries.join('\n')}\n} as const\n`,
    'utf8',
  )
}

function writeGenerated(atlases: Record<string, Record<string, string>>) {
  fs.mkdirSync(generatedRoot, { recursive: true })

  const atlasLines = Object.keys(atlases)
    .sort()
    .map((name) => `  ${name}: "/assets/${name}.json",`)
    .join('\n')

  const texturesBlocks = Object.entries(atlases)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([atlas, frames]) => {
      const frameLines = Object.entries(frames)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([prop, frame]) => `    ${prop}: "${frame}",`)
        .join('\n')
      return `  ${atlas}: {\n${frameLines}\n  },`
    })
    .join('\n')

  fs.writeFileSync(
    path.join(generatedRoot, 'Atlases.ts'),
    `export const Atlases = {\n${atlasLines}\n} as const\n\nexport type AtlasName = keyof typeof Atlases\n`,
    'utf8',
  )

  fs.writeFileSync(
    path.join(generatedRoot, 'Textures.ts'),
    `export const Textures = {\n${texturesBlocks}\n} as const\n\nexport type TextureAtlas = keyof typeof Textures\n`,
    'utf8',
  )

  fs.writeFileSync(
    path.join(generatedRoot, 'index.ts'),
    `export { Atlases } from './Atlases'\nexport type { AtlasName } from './Atlases'\nexport { Textures } from './Textures'\nexport type { TextureAtlas } from './Textures'\nexport { EmbeddedSpritesheets, EmbeddedImages } from './embeddedAssets'\nexport type { EmbeddedAtlasName, EmbeddedSpritesheet } from './embeddedAssets'\nexport { FrameWindow } from './FrameWindow'\n`,
    'utf8',
  )
}

async function packAtlas(atlasName: string, atlasDir: string) {
  const images = collectImages(atlasDir)
  if (images.length === 0) {
    return null
  }

  const files = await packAsync(
    images.map(({ path: imagePath, contents }) => ({ path: imagePath, contents })),
    {
      textureName: atlasName,
      width: 2048,
      height: 2048,
      fixedSize: false,
      padding: 2,
      allowRotation: false,
      detectIdentical: true,
      allowTrim: true,
      exporter: 'Pixi',
      removeFileExtension: true,
      prependFolderName: false,
    } as Parameters<typeof packAsync>[1],
  )

  for (const file of files) {
    fs.writeFileSync(path.join(outRoot, file.name), file.buffer)
  }

  const frames: Record<string, string> = {}
  for (const image of images) {
    frames[toPropName(image.frameKey)] = image.frameKey
  }

  return frames
}

async function main() {
  fs.mkdirSync(outRoot, { recursive: true })
  fs.rmSync(outRoot, { recursive: true, force: true })
  fs.mkdirSync(outRoot, { recursive: true })

  if (!fs.existsSync(rawRoot)) {
    fs.mkdirSync(rawRoot, { recursive: true })
  }

  const atlasDirs = fs
    .readdirSync(rawRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())

  const atlases: Record<string, Record<string, string>> = {}
  const manifestBundles: Array<{
    name: string
    assets: Array<string | { alias: string; src: string }>
  }> = []

  for (const dir of atlasDirs) {
    const frames = await packAtlas(dir.name, path.join(rawRoot, dir.name))
    if (!frames) continue
    atlases[dir.name] = frames
    manifestBundles.push({
      name: dir.name,
      assets: [
        {
          alias: dir.name,
          src: `/assets/${dir.name}.json`,
        },
      ],
    })
  }

  const manifest = {
    bundles: manifestBundles,
  }

  fs.writeFileSync(path.join(outRoot, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8')
  writeGenerated(atlases)
  writeEmbeddedAssets(Object.keys(atlases))

  console.log(`Packed ${Object.keys(atlases).length} atlas(es)`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
